

spring:
  datasource:
    #    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/backendapi
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: ICT
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
app:
  token:
    secret: m#MySecret
    issuer: BackendService

server:
  port : 8080