

spring:
  datasource:
    #    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/backendapi
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: ICT
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: projectrecycle05
    password: tbqwanmrdaptupjn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  token:
    secret: m#MySecret
    issuer: BackendService
  login-social:
    user-id: ccd6bcd9-ed08-4fb5-b05a-29f27ced5375
  email:
    from: projectrecycle05@gmail.com

server:
  port : 8080